"""
Django settings for audio_forgery_project project.

Generated by 'django-admin startproject' using Django 5.2.15.
Production-hardened for Render deployment.
"""

import os
import sys
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Set Project Root to the parent directory to allow access to ML pipeline code and model output files
PROJECT_ROOT = BASE_DIR.parent

# Append project root to sys.path so that django app can import 'audio_forgery' and 'models' packages
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

# ── Security ─────────────────────────────────────────────────────────────────
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY", "django-insecure-i++z^$0^mjznpn=($rqtc(2cn-jmyv5s81lgn#5od@1v)of%m=")

# Detect if we're running on Render
ON_RENDER = os.getenv("RENDER", "").lower() in ("true", "1", "yes")

# Set DEBUG=False on Render unless explicitly overridden
DEBUG = os.getenv("DJANGO_DEBUG", "False" if ON_RENDER else "True").lower() in ("true", "1", "yes")

# Allow all hosts on Render (ALLOWED_HOSTS is enforced by Render's TLS proxy anyway)
RENDER_EXTERNAL_HOSTNAME = os.environ.get("RENDER_EXTERNAL_HOSTNAME")
ALLOWED_HOSTS = [
    "localhost",
    "127.0.0.1",
    "audio-forgery-detection-backend.onrender.com",
]
if RENDER_EXTERNAL_HOSTNAME:
    ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME)
# Allow * in dev
if not ON_RENDER or DEBUG:
    ALLOWED_HOSTS = ["*"]

# Application definition
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "corsheaders",
    "rest_framework",
    "detector.apps.DetectorConfig",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",     # ← WhiteNoise (after SecurityMiddleware)
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",           # ← CORS before CommonMiddleware
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "audio_forgery_project.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "audio_forgery_project.wsgi.application"
ASGI_APPLICATION = "audio_forgery_project.asgi.application"

# Database (Minimal sqlite db, stateless APIs mostly)
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

# Internationalization
LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True

# ── Static Files (WhiteNoise) ─────────────────────────────────────────────────
STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

MEDIA_URL = "media/"
MEDIA_ROOT = BASE_DIR / "media"

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# ── CORS ──────────────────────────────────────────────────────────────────────
# Hardcode both the local dev origin and the actual Render frontend
_cors_origins = [
    "http://localhost:5173",
    "http://127.0.0.1:5173",
    # Actual deployed frontend
    "https://audio-forgery-detection-frontend.onrender.com",
]

# Also support FRONTEND_URL env var for flexibility
FRONTEND_URL = os.getenv("FRONTEND_URL", "")
if FRONTEND_URL and FRONTEND_URL.rstrip("/") not in _cors_origins:
    _cors_origins.append(FRONTEND_URL.rstrip("/"))

# In development allow all origins
if not ON_RENDER:
    CORS_ALLOW_ALL_ORIGINS = True
else:
    CORS_ALLOWED_ORIGINS = _cors_origins

CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_HEADERS = [
    "accept",
    "accept-encoding",
    "authorization",
    "content-type",
    "dnt",
    "origin",
    "user-agent",
    "x-csrftoken",
    "x-requested-with",
]

# ── REST Framework ─────────────────────────────────────────────────────────────
REST_FRAMEWORK = {
    "DEFAULT_RENDERER_CLASSES": [
        "rest_framework.renderers.JSONRenderer",
        "rest_framework.renderers.BrowsableAPIRenderer",
    ],
    "UNAUTHENTICATED_USER": None,
}

# ── ML Model Paths ─────────────────────────────────────────────────────────────
ML_CONFIG_PATH = os.getenv("ML_CONFIG_PATH", str(PROJECT_ROOT / "model2_resnet/configs/config.yaml"))

# HuggingFace Hub repo for model downloads (used by build.sh)
HF_REPO_ID = os.getenv("HF_REPO_ID", "Hkm2003/audio-forgery-models-bucket")
